/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Davidson
 */
public class telaPrincipal extends javax.swing.JFrame {

    ArquivoTxt txt = new ArquivoTxt();
    public telaPrincipal() {        
            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but_cadastrar = new javax.swing.JButton();
        but_modificar = new javax.swing.JButton();
        but_relatorio = new javax.swing.JButton();
        but_pagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(404, 400));
        setPreferredSize(new java.awt.Dimension(410, 400));
        getContentPane().setLayout(null);

        but_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastrar (2).png"))); // NOI18N
        but_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(but_cadastrar);
        but_cadastrar.setBounds(0, 0, 130, 140);

        but_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar e Deletar.png"))); // NOI18N
        but_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(but_modificar);
        but_modificar.setBounds(270, 0, 130, 140);

        but_relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Relatorio (2).png"))); // NOI18N
        but_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_relatorioActionPerformed(evt);
            }
        });
        getContentPane().add(but_relatorio);
        but_relatorio.setBounds(0, 220, 130, 140);

        but_pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pagamento.png"))); // NOI18N
        but_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_pagarActionPerformed(evt);
            }
        });
        getContentPane().add(but_pagar);
        but_pagar.setBounds(270, 220, 130, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cadastrarActionPerformed
       Cadastrar a = new Cadastrar();
       a.setVisible(true);
    }//GEN-LAST:event_but_cadastrarActionPerformed

    private void but_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_modificarActionPerformed
        updateEdelete a = new updateEdelete();
        a.setVisible(true);
    }//GEN-LAST:event_but_modificarActionPerformed

    private void but_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_relatorioActionPerformed
       Relatorio a = new Relatorio();
       a.setVisible(true);
    }//GEN-LAST:event_but_relatorioActionPerformed

    private void but_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_pagarActionPerformed
        pagamento a = new pagamento();
       a.setVisible(true);
    }//GEN-LAST:event_but_pagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_cadastrar;
    private javax.swing.JButton but_modificar;
    private javax.swing.JButton but_pagar;
    private javax.swing.JButton but_relatorio;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
